# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Get firebase-tools
        run: sudo npm install -g firebase-tools
      - name: deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}